/**
 * @file cities_data.h
 * @brief Populated places data loaded from data/cities.bin
 *
 * Stores world cities (pop > 100K) with tile coordinates, population
 * tier, and capital flags. Provides spatial-grid queries for viewport
 * rendering at appropriate zoom levels.
 *
 * Data is generated by tools/generate_cities.py from Natural Earth.
 */
#ifndef CIV_CITIES_DATA_H
#define CIV_CITIES_DATA_H

#include "../../common.h"
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define CIV_CITY_NAME_MAX      64
#define CIV_CITIES_MAX         8192

/* City tier: determines when the city label appears */
enum {
    CIV_CITY_TIER_MEGA   = 0,  /* pop > 10M */
    CIV_CITY_TIER_LARGE  = 1,  /* pop 1M-10M */
    CIV_CITY_TIER_MEDIUM = 2,  /* pop 100K-1M */
    CIV_CITY_TIER_SMALL  = 3   /* pop < 100K */
};

/* ── Single city entry ────────────────────────────────────────── */
typedef struct {
    char        name[CIV_CITY_NAME_MAX];
    char        iso_a2[3];
    uint16_t    tile_x, tile_y;
    uint32_t    population;
    uint8_t     capital_flag;   /* bit 0: national capital */
    uint8_t     tier;           /* CIV_CITY_TIER_* */
} civ_city_data_t;

/* ── Cities data ──────────────────────────────────────────────── */
typedef struct {
    civ_city_data_t *cities;
    uint32_t         count;
    uint32_t         capacity;
    uint32_t         map_width, map_height;

    /* Spatial index: 32x32 grid cells over the world map.
       Each cell stores indices into the cities[] array. */
    struct {
        uint32_t *indices;
        uint32_t  count;
        uint32_t  capacity;
    } grid[32][32];
} civ_cities_data_t;

/* ── Lifecycle ────────────────────────────────────────────────── */
civ_cities_data_t *civ_cities_data_create(uint32_t map_w, uint32_t map_h);
void               civ_cities_data_destroy(civ_cities_data_t *cd);

/* Load data/cities.bin */
civ_result_t       civ_cities_data_load(civ_cities_data_t *cd,
                                        const char *filepath);

/* ── Queries ──────────────────────────────────────────────────── */

/* Get cities visible within a tile viewport.
   Returns a caller-freed array of pointers. */
const civ_city_data_t **civ_cities_query_tiles(
    const civ_cities_data_t *cd,
    int32_t tile_x, int32_t tile_y,
    int32_t tile_w, int32_t tile_h,
    uint32_t min_tier,         /* only cities at or above this tier */
    uint32_t *out_count);

/* Get cities for a specific country (by ISO-A2) */
const civ_city_data_t **civ_cities_for_country(
    const civ_cities_data_t *cd,
    const char *iso_a2,
    uint32_t *out_count);

/* Free query result */
void civ_cities_free_result(const civ_city_data_t **result);

#ifdef __cplusplus
}
#endif
#endif
