/**
 * @file nations_data.h
 * @brief Master nation index loaded from data/nations.bin
 *
 * Provides lookup of real-world nation metadata (name, ISO codes,
 * continent, population, GDP, capital coords, assigned color).
 * Data is generated by tools/generate_nations.py from Natural Earth.
 */
#ifndef CIV_NATIONS_DATA_H
#define CIV_NATIONS_DATA_H

#include "../../common.h"
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define CIV_NATION_NAME_MAX     64
#define CIV_NATION_DATA_MAX     256

/* ── Single nation data entry ─────────────────────────────────── */
typedef struct {
    uint32_t    id;
    char        iso_a3[4];        /* null-terminated 3-char code */
    char        iso_a2[3];        /* null-terminated 2-char code */
    char        name[CIV_NATION_NAME_MAX];
    uint32_t    color_rgb;        /* 0xRRGGBB */
    char        continent[32];
    char        region[32];
    char        subregion[32];
    uint32_t    population_est;
    uint32_t    gdp_est_millions; /* GDP in millions USD */
    float       capital_lon;
    float       capital_lat;
    float       centroid_lon;     /* placeholder */
    float       centroid_lat;     /* placeholder */
    float       area_sqkm;
} civ_nation_data_t;

/* ── Master nation index ──────────────────────────────────────── */
typedef struct {
    civ_nation_data_t  *nations;
    uint32_t            count;
    uint32_t            capacity;
} civ_nations_data_t;

/* ── Lifecycle ────────────────────────────────────────────────── */
civ_nations_data_t *civ_nations_data_create(void);
void                civ_nations_data_destroy(civ_nations_data_t *nd);

/* Load data/nations.bin */
civ_result_t        civ_nations_data_load(civ_nations_data_t *nd,
                                          const char *filepath);

/* ── Lookup ───────────────────────────────────────────────────── */
const civ_nation_data_t *civ_nations_data_get_by_id(
    const civ_nations_data_t *nd, uint32_t id);
const civ_nation_data_t *civ_nations_data_get_by_iso(
    const civ_nations_data_t *nd, const char *iso_a3);
const civ_nation_data_t *civ_nations_data_get_by_name(
    const civ_nations_data_t *nd, const char *name);

#ifdef __cplusplus
}
#endif
#endif
