/**
 * @file resource_map.h
 * @brief Per-tile resource presence loaded from data/resources.bin
 *
 * Stores sparse per-resource-type deposit arrays with quantity and
 * quality. 20 resource types covering minerals, energy, and materials.
 * Data is generated by tools/generate_resources.py from geological surveys.
 */
#ifndef CIV_RESOURCE_MAP_H
#define CIV_RESOURCE_MAP_H

#include "../../common.h"
#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ── Resource type enum (must match generate_resources.py) ────── */
typedef enum {
    CIV_RESOURCE_OIL          = 0,
    CIV_RESOURCE_NATURAL_GAS  = 1,
    CIV_RESOURCE_COAL         = 2,
    CIV_RESOURCE_IRON         = 3,
    CIV_RESOURCE_COPPER       = 4,
    CIV_RESOURCE_BAUXITE      = 5,
    CIV_RESOURCE_GOLD         = 6,
    CIV_RESOURCE_SILVER       = 7,
    CIV_RESOURCE_URANIUM      = 8,
    CIV_RESOURCE_DIAMONDS     = 9,
    CIV_RESOURCE_PHOSPHATES   = 10,
    CIV_RESOURCE_RARE_EARTH   = 11,
    CIV_RESOURCE_LITHIUM      = 12,
    CIV_RESOURCE_COBALT       = 13,
    CIV_RESOURCE_TIN          = 14,
    CIV_RESOURCE_ZINC         = 15,
    CIV_RESOURCE_LEAD         = 16,
    CIV_RESOURCE_NICKEL       = 17,
    CIV_RESOURCE_CHROMITE     = 18,
    CIV_RESOURCE_MANGANESE    = 19,
    CIV_RESOURCE_COUNT        = 20
} civ_resource_type_t;

/* ── Single deposit entry ─────────────────────────────────────── */
typedef struct {
    uint16_t x, y;
    uint16_t quantity;     /* arbitrary units per resource type */
    uint8_t  quality;      /* 0-100 */
} civ_resource_deposit_t;

/* ── Resource map ─────────────────────────────────────────────── */
typedef struct {
    /* Sparse arrays: deposits_by_type[resource_type] is a flat
       array of deposits for that resource type */
    civ_resource_deposit_t *deposits[CIV_RESOURCE_COUNT];
    uint16_t                deposit_count[CIV_RESOURCE_COUNT];
    uint32_t                width, height;
} civ_resource_map_t;

/* ── Lifecycle ────────────────────────────────────────────────── */
civ_resource_map_t *civ_resource_map_create(uint32_t width, uint32_t height);
void                civ_resource_map_destroy(civ_resource_map_t *rm);

/* Load data/resources.bin */
civ_result_t        civ_resource_map_load(civ_resource_map_t *rm,
                                          const char *filepath);

/* ── Queries ──────────────────────────────────────────────────── */
/* Check if a resource type is present at a tile */
bool     civ_resource_map_has_type(const civ_resource_map_t *rm,
                                   int32_t x, int32_t y,
                                   civ_resource_type_t type);

/* Get quantity at tile (summed across nearby deposits) */
uint16_t civ_resource_map_get_quantity(const civ_resource_map_t *rm,
                                       int32_t x, int32_t y,
                                       civ_resource_type_t type);

/* Get best quality at tile */
uint8_t  civ_resource_map_get_quality(const civ_resource_map_t *rm,
                                      int32_t x, int32_t y,
                                      civ_resource_type_t type);

/* Sum all quantities for all resource types at a tile */
uint16_t civ_resource_map_total_at_tile(const civ_resource_map_t *rm,
                                        int32_t x, int32_t y);

/* Count how many distinct resource types are present at a tile */
int      civ_resource_map_type_count_at_tile(const civ_resource_map_t *rm,
                                             int32_t x, int32_t y);

/* Friendly names for resource types */
const char *civ_resource_type_name(civ_resource_type_t type);

#ifdef __cplusplus
}
#endif
#endif
