# example_configs/doctrines.yaml
# Example doctrine configuration
blitzkrieg:
  era: industrial
  effects:
    combat_bonus: 1.3
    movement_bonus: 1.2
    supply_efficiency: 0.9
    research_cost: 200
  requirements:
    - mechanized_warfare
    - radio_communications
  compatible_units:
    - armor
    - motorized_infantry
    - close_air_support
  special_rules:
    - breakthrough
    - encirclement_bonus

defense_in_depth:
  era: industrial
  effects:
    combat_bonus: 0.9
    movement_bonus: 0.8
    supply_efficiency: 1.2
    research_cost: 180
  requirements:
    - entrenchment
    - artillery
  compatible_units:
    - infantry
    - artillery
    - engineers
  special_rules:
    - prepared_defenses
    - counterattack_bonus

maneuver_warfare:
  era: modern
  effects:
    combat_bonus: 1.2
    movement_bonus: 1.3
    supply_efficiency: 1.0
    research_cost: 250
  requirements:
    - combined_arms
    - satellite_intel
  compatible_units:
    - all
  special_rules:
    - rapid_redeployment
    - initiative_bonus