# example_configs/technology.yaml
# Example technology tree configuration
basic_training:
  category: infantry
  research_cost: 50
  prerequisites: []
  effects:
    infantry_combat: 1.1
    morale: 1.05
  era: 1

entrenchment:
  category: infantry
  research_cost: 75
  prerequisites: [basic_training]
  effects:
    defense_bonus: 1.2
    entrenchment_speed: 1.5
  era: 1

mechanized_warfare:
  category: armor
  research_cost: 200
  prerequisites: [automotive_industry]
  effects:
    armor_combat: 1.3
    movement_speed: 1.2
    fuel_efficiency: 0.9
  era: 2

combined_arms:
  category: communications
  research_cost: 300
  prerequisites: [radio_communications, mechanized_warfare]
  effects:
    combined_arms_bonus: 1.25
    coordination: 1.3
  era: 3

nuclear_weapons:
  category: aerial
  research_cost: 1000
  prerequisites: [nuclear_physics, advanced_avionics]
  effects:
    strategic_deterrence: 2.0
    diplomatic_weight: 1.5
  era: 4